Repository Pogakco/BE, pull requests merged in 2024-07, with the labels that each got.

#3 Feature/#2 방 목록 API 추가
  app.js
  constants.js
  controllers/roomController.js
  repositories/roomListRepository.js
  routers/roomRouter.js
  services/roomListService.js
  validators/roomValidator.js
Labels: feature

#6 fix(userRouter): prefix url을 "/api"에서 "/"로 변경
  app.js
Labels: fix

#8 feat(room): 방 개별 조회 및 참여자 조회 API 구현
  controllers/roomController.js
  repositories/roomRepository.js
  routers/roomRouter.js
  services/roomService.js
  validators/roomValidator.js
Labels: feature

#10 feat(timer): 포모도로 타이머 소켓 기능 구현
  app.js
  constants.js
  package-lock.json
  package.json
  repositories/roomRepository.js
  repositories/timerRepository.js
  services/roomService.js
  services/timerService.js
  socket/helpers/createIo.js
  socket/helpers/getAllLinkedUserIdsFromNamespace.js
  socket/helpers/getUserIdFromSocket.js
  socket/room-detail/handlers/onRoomDetailConnection.js
  socket/room-detail/handlers/onRoomDetailDisconnect.js
  socket/room-detail/handlers/onStartCycles.js
  socket/room-detail/helpers/calculateMs.js
  socket/room-detail/helpers/getFinishCyclesTimeout.js
  socket/room-detail/helpers/getPomodoroInterval.js
  socket/room-detail/helpers/getRoomIdFromNamespace.js
  socket/room-detail/helpers/getRoomInfoSafety.js
  socket/room-detail/helpers/startTimer.js
Labels: feature

#15 feat(user): 이메일, 닉네임을 각각 중복 체크하는 api 구현
  controllers/userController.js
  routers/userRouter.js
  validators/userValidator.js
Labels: feature

#16 feat(user-validator): nickname, password 필드에 정규 표현식 유효성 검사 적용
  validators/userValidator.js
Labels: feature

#18 feat(user): 내 프로필 api 구현
  controllers/userController.js
  repositories/userRepository.js
  routers/userRouter.js
  services/userService.js
Labels: feature

#19 feat(roomList): 참여한 방 목록 조회 api 구현
  controllers/roomController.js
  repositories/roomListRepository.js
  routers/roomRouter.js
  services/roomListService.js
Labels: feature

#21 feat(room): 방 생성하기 API 구현
  controllers/roomController.js
  repositories/roomRepository.js
  repositories/timerRepository.js
  routers/roomRouter.js
  services/roomService.js
  validators/roomValidator.js
Labels: feature

#23 fix(roomValidator): 방 생성 시 유효성 검사 범위 수정
  validators/roomValidator.js
Labels: fix

#27 feat(roomList): 방 목록과 참여한 방 목록에 isJoined 필드 추가
  controllers/roomController.js
  repositories/roomListRepository.js
  routers/roomRouter.js
  services/roomListService.js
Labels: feature

#29 refactor(userRoom): userRoomRepository로 메서드 분리
  repositories/roomRepository.js
  repositories/userRoomRepository.js
  services/roomService.js
  services/timerService.js
Labels: refactor

#32 feat(timer): 타이머 소켓 추가기능 구현
  constants.js
  repositories/userRoomRepository.js
  services/timerService.js
  socket/room-detail/handlers/onRoomDetailConnection.js
  socket/room-detail/handlers/onRoomDetailDisconnect.js
  socket/room-detail/helpers/calculateMs.js
  socket/room-detail/helpers/getFinishCyclesTimeout.js
Labels: feature

#36 feat(room): 방 참가하기 API 구현
  controllers/roomController.js
  repositories/userRoomRepository.js
  routers/roomRouter.js
  services/roomService.js
Labels: feature

#39 feat(room): 방 나가기 api 구현
  controllers/roomController.js
  repositories/userRoomRepository.js
  routers/roomRouter.js
  services/roomService.js
Labels: feature

#40 feat(user): 비밀번호 확인 api 구현
  controllers/userController.js
  routers/userRouter.js
  services/userService.js
  validators/userValidator.js
Labels: feature

#41 refactor(room): findRoomById 메서드 반환 변경
  controllers/roomController.js
  repositories/roomRepository.js
Labels: refactor

#44 feat(user): 프로필 수정 api 구현
  config/aws-config.js
  constants.js
  controllers/helpers/multerErrorHandler.js
  controllers/userController.js
  helpers/deleteFileFromS3.js
  helpers/uploadFileToS3.js
  middlewares/multerUpload.js
  package-lock.json
  package.json
  repositories/userRepository.js
  routers/userRouter.js
  services/userService.js
  utils/getPathnameFromUrl.js
  utils/trim.js
  validators/helpers/imageFileChain.js
  validators/userValidator.js
Labels: feature

#45 feat(room): 방 삭제하기 api 구현
  controllers/roomController.js
  repositories/roomRepository.js
  routers/roomRouter.js
  services/roomService.js
Labels: feature

#51 feat(userRoom): 참여자 목록을 활성화 상태와 뽀모도로 카운트 순으로 정렬
  repositories/userRoomRepository.js
Labels: feature

#52 feat(room): 집중 중인 방 참여 시 에러 처리 추가
  controllers/roomController.js
  repositories/roomRepository.js
Labels: feature

#57 feat(timer-socket): 방 삭제하기 소켓 이벤트 구현
  constants.js
  controllers/roomController.js
  routers/roomRouter.js
  services/roomService.js
  socket/room-detail/handlers/onDeleteRoom.js
  socket/room-detail/handlers/onRoomDetailConnection.js
  socket/room-detail/handlers/onStartCycles.js
  socket/room-detail/helpers/getRoomInfoSafety.js
Labels: feature

#53 feat(auth): 인증 리프레시 토큰 추가
  app.js
  constants.js
  controllers/userController.js
  middlewares/defaultErrorHandler.js
  middlewares/loginRequired.js
  package-lock.json
  package.json
  repositories/userRepository.js
  routers/roomRouter.js
  routers/userRouter.js
  services/userService.js
  socket/room-detail/helpers/calculateMs.js
  validators/middlewares/injectUserId.js
  validators/middlewares/loginRequired.js
Labels: feature

#64 fix(sql): Left Join에 Where절을 사용하면서 Count문이 잘 작동하지 않는 문제를 서브 쿼리를 사용하여 해결
  repositories/roomListRepository.js
Labels: fix

#66 feat(db): connection 연결 최적화
  controllers/roomController.js
  db/pool.js
  services/roomService.js
  services/timerService.js
  socket/room-detail/handlers/onRoomDetailDisconnect.js
  socket/room-detail/handlers/onStartCycles.js
  socket/room-detail/helpers/getFinishCyclesTimeout.js
  socket/room-detail/helpers/getPomodoroInterval.js
  socket/room-detail/helpers/startTimer.js
Labels: feature

#70 feat(room): 방 제목, 방 설명 글자수 유효성 검사 추가
  validators/roomValidator.js
Labels: feature

#75 fix(socket): 타이머 소켓에 연결될 때 연결된 유저 정보, 참여자 정보 값이 비로그인 유저도 동기화 되도록 수정
  socket/room-detail/handlers/onRoomDetailConnection.js
Labels: fix

#77 feat(feedback): 피드백 api 구현
  app.js
  controllers/feedbackController.js
  repositories/feedbackRepository.js
  routers/feedbackRouter.js
  services/feedbackService.js
  validators/feedbackValidator.js
Labels: feature

#71 fix(timer-socket): 타이머 소켓 인증 로직 수정
  app.js
  constants.js
  middlewares/loginRequired.js
  services/userService.js
  socket/helpers/getAllLinkedUserIdsFromNamespace.js
  socket/helpers/getUserIdFromSocket.js
  socket/middlewares/socketLoginRequired.js
  socket/room-detail/handlers/onRoomDetailConnection.js
  socket/room-detail/helpers/registerRoomDetailEventsInterceptor.js
Labels: fix

#82 feat(timer-socket): 타이머 시작시점에도 참여중인 유저정보 동기화 되도록 변경, 딜레이 시간 2초로 축소
  socket/room-detail/helpers/calculateMs.js
  socket/room-detail/helpers/startTimer.js
Labels: feature

#76 feat(timer): 운영 환경에서 타이머가 분 단위로 작동하게 변경
  socket/room-detail/helpers/calculateMs.js
Labels: feature

#84 refactor: 사이클 진행 중인 방에 대한 참여, 삭제 에러 메시지 수정
  constants.js
  controllers/roomController.js
Labels: refactor

#86 refactor(roomValidator): 뽀모도로 사이클 횟수 유효성 검사 값 수정
  validators/roomValidator.js
Labels: refactor

#88 feat(timer-socket): 타이머 소켓에 연결 될 때 isRunning 상태를 동기화 하도록 변경
  socket/room-detail/handlers/onRoomDetailConnection.js
Labels: feature

#90 feat(timer-socket):서버 현재 시각을 알려주는 소켓 이벤트 추가
  constants.js
  socket/room-detail/handlers/onGetServerCurrentTime.js
  socket/room-detail/handlers/onRoomDetailConnection.js
Labels: feature

#93 feat(timer-socket): 기존 이벤트 제거하고 서버 현재 시각 연동 이벤트 추가
  constants.js
  socket/room-detail/handlers/onGetServerCurrentTime.js
  socket/room-detail/handlers/onRoomDetailConnection.js
Labels: feature

#94 feat(roomList): 방 목록 최신순으로 정렬
  repositories/roomListRepository.js
Labels: feature

#97 chore: docker의 timezone을 한국 시간대로 변경
  compose.yaml
Labels: chore
